services:
  rust-server:
    build:
      context: Ingestion/
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    depends_on:
      - timescaledb
    environment:
      - DATABASE_URL=postgres://username:password@timescaledb:5432/mydatabase

  timescaledb:
    image: timescale/timescaledb:latest-pg16
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase
    ports:
      - "5432:5432"
#    volumes:
#      - timescaledb_data:/var/lib/postgresql/data

#volumes:
#  timescaledb_data: